### ISSUE TITLE
Not an issue but an idea: MB Mod

### ISSUE THREAD

**Issue by captainaxron** [pizzaboxer/bloxstrap#64]
Instead of using unreliable Reshade, (or really any roblox shader plugin) there could be a motionblur mod! Not the one in Reshade, but kinda like how Lunar Client or Badlion Client does in minecraft. It would really add into the smoothness and could pair well with roblox’s fps unlocked. Also, if hardware is not capable of unlocking frames and having a good experience, the motion blur mod could make the experience just as smooth with 60 frames. Good idea: or not?

**Comment by pizzaboxer** [comment]
I don't really know of anyone who develops a motion blur mod for Roblox. Also, I've never really heard about Reshade being unreliable?

**Comment by captainaxron** [comment]
Reshade doesn’t work with roblox updates and thus making you reinstall every time roblox recives a update. Also reshade can cause significant lag due to all the other unnecessary features making it bloated if all you want to do is add motionblur.

**Comment by pizzaboxer** [comment]
> Reshade doesn’t work with roblox updates thus making you reinstall every time roblox recives a update.

That's not necessarily Reshade's fault. Roblox's install path changes every time it updates, so of course once Roblox updates, Reshade is gonna vanish and require a reinstall. If you had, say, something that replaces the Roblox launcher (hmm i wonder what could do that), you could easily make it so Reshade is fixed after every Roblox update. In fact, that's what Roshade Pro basically does.

I've been thinking about adding Reshade support to Bloxstrap, but I don't know, I guess I kinda just never really saw the use for it. It's likely going to be on my todo list though.

**Comment by captainaxron** [comment]
Ok, thanks for the info. I guess my question was a bit dumb. I think Reshade support would be amazing. Hope to see it in the future!

**Comment by TamTamCha** [comment]
How will the patcher work?

**Comment by pizzaboxer** [comment]
dude this was over a year ago

**Comment by luigiWithDaPoltergust** [comment]
how does it work?? i can't find out how to get it working, roshade still doesn't work with bloxstrap

**Comment by pizzaboxer** [comment]
https://bloxshade.com
